### ISSUE TITLE
mlcp import

### ISSUE THREAD

**Issue by sammefford** [marklogic/data-movement#1]
Integrate mlcp import functionality under this API:

    DataMovementManager {
      ...
      JobTicket<ImportJobReport> import(ImportDefinition def)
      ImportDefinition newImportDefinition()
    }

    ImportDefinition implements JobDefinition<ImportDefinition> {
      ImportDefinition jobName(String jobName)
      ImportDefinition maxSplitSize(int splitSize)
      ImportDefinition minSplitSize(int splitSize)
      ImportDefinition inputFilePath(String path)
      ImportDefinition inputFilePattern(String pattern)
      ...
      ImportDefinition onBatchSuccess(ImportSuccessListener listener)
      ImportDefinition onBatchFailure(ImportFailureListener listener)
    }

    ImportSuccessListener {
      void batchSuccess(ImportDocument[] docs)
    }

    ImportDocument {
      String getUri()
      File   getSourceFile()
    }

    ImportFailureListener {
      void batchFailure(ImportFailure failure)
    }

    ImportFailure {
      String[]  getBatchUris()
      Exception getException()
    }

**Comment by sammefford** [comment]
Done (commit d9cb9a5).

Here's where the API landed:

    DataMovementManager {
      ...
      JobTicket startJob(ImportDefinition def)
      ImportDefinition  newImportDefinition()
    }

    ImportDefinition implements JobDefinition<ImportDefinition> {
      ImportDefinition withContentEncoding(String charset)
      ImportDefinition withInputFilePath(String path)
      ImportDefinition withInputFilePattern(String pattern)
      <T extends ImportDefinition> T withInputFileType(InputFileType<T> inputFileType)
      ImportDefinition withMaxSplitSize(long splitSize)
      ImportDefinition withMinSplitSize(long splitSize)
      ImportDefinition withOutputCleanDir(boolean cleanDirectory)
      ImportDefinition withOutputCollections(String... collections)
      ImportDefinition withOutputDirectory(String directory)
      ImportDefinition withOutputPartition(String partition)
      ImportDefinition withOutputPermissions(String role, String capability)
      ImportDefinition withOutputPermissions(String role, String capability, String... roleCapabilityPairs)
      ImportDefinition withOutputQuality(int quality)
      ImportDefinition withOutputUriPrefix(String prefix)
      ImportDefinition withOutputUriReplace(String pattern, String replacement)
      ImportDefinition withOutputUriReplace(String pattern, String replacement, String... patternReplacementPairs)
      ImportDefinition withOutputUriSuffix(String suffix)
      ImportDefinition withTemporalCollection(String collection)
      ImportDefinition withTransform(DataMovementTransform transform)
      ImportDefinition withTolerateErrors(boolean tolerateErrors)
      ImportDefinition withXmlRepairLevel(ImportDefinition.XmlRepairLevel repairLevel)
      ImportDefinition withFastload(boolean fastload)
      ImportDefinition onBatchSuccess(BatchListener<ImportEvent> listener)
      ImportDefinition onBatchFailure(BatchFailureListener<ImportEvent> listener)

      InputFileType<T extends ImportDefinition> {
        InputFileType<AggregatesImportDefinition>    AGGREGATES
        InputFileType<ArchiveImportDefinition>       ARCHIVE
        InputFileType<DelimitedJsonImportDefinition> DELIMITED_JSON
        InputFileType<DelimitedTextImportDefinition> DELIMITED_TEXT
        InputFileType<DocumentsImportDefinition>     DOCUMENTS
        InputFileType<ForestImportDefinition>        FOREST
        InputFileType<RdfImportDefinition>           RDF
        InputFileType<SequenceFileImportDefinition>  SEQUENCE_FILE
      }
    }

    enum ImportDefinition.XmlRepairLevel {
      DEFAULT, FULL, NONE
    }

    AggregatesImportDefinition extends ImportDefinition {
      AggregatesImportDefinition withAggregateRecordElement(String name)
      AggregatesImportDefinition withAggregateRecordNamespace(String namespace)
      AggregatesImportDefinition withFilenameAsCollection(boolean filenameAsCollection)
      AggregatesImportDefinition withInputCompressed(boolean compressed)
      AggregatesImportDefinition withInputCompressionCodec(String codec)
      AggregatesImportDefinition withUriId(String name)
    }

    ArchiveImportDefinition extends ImportDefinition {
      ArchiveImportDefinition withArchiveMetadataOptional(boolean optional)
      ArchiveImportDefinition withCopyCollections(boolean copy)
      ArchiveImportDefinition withCopyPermissions(boolean copy)
      ArchiveImportDefinition withCopyProperties (boolean copy)
      ArchiveImportDefinition withCopyQuality    (boolean copy)
      ArchiveImportDefinition withFilenameAsCollection(boolean filenameAsCollection)
      ArchiveImportDefinition withInputCompressed(boolean compressed)
      ArchiveImportDefinition withInputCompressionCodec(String codec)
    }

    DelimitedJsonImportDefinition extends ImportDefinition {
      DelimitedJsonImportDefinition putDataType(String property, DataType type)
      DelimitedJsonImportDefinition withDelimiter(String delimeter)
      DelimitedJsonImportDefinition withDelimitedRootName(String name)
      DelimitedJsonImportDefinition withFilenameAsCollection(boolean filenameAsCollection)
      DelimitedJsonImportDefinition withInputCompressed(boolean compressed)
      DelimitedJsonImportDefinition withInputCompressionCodec(String codec)
      DelimitedJsonImportDefinition withGenerateUri(boolean generate)
      DelimitedJsonImportDefinition withNamespace(String namespace)
      DelimitedJsonImportDefinition withOutputLanguage(String xmlLang)
      DelimitedJsonImportDefinition withSplitInput(boolean split)
      DelimitedJsonImportDefinition withUriId(String name)
    }

    enum DelimitedJsonImportDefinition.DataType { STRING, NUMBER, BOOLEAN }

    DelimitedTextImportDefinition extends ImportDefinition {
      DelimitedJsonImportDefinition putDataType(String property, DataType type)
      DelimitedTextImportDefinition withDocumentType(Format format)
      DelimitedTextImportDefinition withFilenameAsCollection(boolean filenameAsCollection)
      DelimitedTextImportDefinition withInputCompressed(boolean compressed)
      DelimitedTextImportDefinition withInputCompressionCodec(String codec)
      DelimitedTextImportDefinition withNamespace(String namespace)
      DelimitedTextImportDefinition withOutputLanguage(String xmlLang)
      DelimitedTextImportDefinition withUriId(String name)
    }

    DocumentsImportDefinition extends ImportDefinition {
      DocumentsImportDefinition withDocumentType(Format format)
      DocumentsImportDefinition withFilenameAsCollection(boolean filenameAsCollection)
      DocumentsImportDefinition withInputCompressed(boolean compressed)
      DocumentsImportDefinition withInputCompressionCodec(String codec)
      DocumentsImportDefinition withStreaming(boolean stream)
    }

    ForestImportDefinition extends ImportDefinition {
      ForestImportDefinition withCollectionFilter(String... forests)
      ForestImportDefinition withDirectoryFilter(String... directories)
      ForestImportDefinition withTypeFilter(String... types)
    }

    RdfImportDefinition extends ImportDefinition {
      RdfImportDefinition withInputCompressed(boolean compressed)
      RdfImportDefinition withInputCompressionCodec(String codec)
      RdfImportDefinition withOutputGraph(String graph)
      RdfImportDefinition withOutputOverrideGraph(String graph)
    }

    SequenceFileImportDefinition extends ImportDefinition {
      SequenceFileImportDefinition withDocumentType(Format format)
      SequenceFileImportDefinition withFilenameAsCollection(boolean filenameAsCollection)
      SequenceFileImportDefinition withInputCompressed(boolean compressed)
      SequenceFileImportDefinition withInputCompressionCodec(String codec)
      SequenceFileImportDefinition withSequenceKeyClass(String className)
      SequenceFileImportDefinition withSequenceValueClass(String className)
      SequenceFileImportDefinition withSequenceValueType(SequenceValueType type)
    }

    enum SequenceFileImportDefinition.SequenceValueType { BYTES_WRITABLE, TEXT }

**Comment by srinathgit** [comment]
Closing this out as DMSDK does not use mlcp
