### ISSUE TITLE
Roll DMSDK into the Java Client API

### ISSUE THREAD

**Issue by jmakeig** [marklogic/data-movement#120]
One of the intents of DMSDK is to provide bulk movement, in the vernacular of the Java Client API, allowing developers to mix and match synch and asynch workloads. As such, DMSDK depends on the Java Client API. The physical separation between the two, however, is more a [reflection of our organizational structure](https://en.wikipedia.org/wiki/Conway%27s_law) than the actual use cases from the customer perspective. As such, I propose we roll DMSDK into the Java Client API and thus provide a single Java API for MarkLogic.

Before we actually do this, let’s figure out the details of how this would work and potential problems.
- Gradle: DMSDK uses Gradle to build and run tests. Java Client API uses Maven. In general, we want to move to Gradle for everything, but this is work.
- Test: How do we integrate regression, Jenkins, etc.?
- Docs?
- Packaging and publishing?

What else?

**Comment by jmakeig** [comment]
Complement of marklogic/java-client-api#465

**Comment by vivekmuniyandi** [comment]
https://github.com/marklogic/java-client-api/commit/cbea16ffcf052ab97a9a2216edd5909d0e55a52b

and 

https://github.com/marklogic/java-client-api/commit/9a818ff3b7849cb8abcfc19370af634ce0528f0c

commits are responsible for moving DMSDK into Java Client API.

**Comment by jmakeig** [comment]
Good stuff. Thanks.
