### ISSUE TITLE
JavaDoc code formatting

### ISSUE THREAD

**Issue by jmakeig** [marklogic/data-movement#130]
I’m loving the  new examples in the JavaDocs. They are something we should definitely invest more in. However, at least in Eclipse, the code is mostly unreadable because it’s formatted as plain old HTML (i.e. no line breaks, collapsed whitespace, default variable-width font).

I think the solution is to wrap the code samples in a `<pre><code>…</code></pre>`:

``` java
/**
 * Facilitates writing uris to a file when necessary because setting [merge
 * timestamp][] and {@link QueryHostBatcher#withConsistentSnapshot
 * withConsistentSnapshot} is not an option, but you need to run DeleteListener
 * or ApplyTransformListener.
 *
 * Example writing uris to disk then running a delete:
 *<pre><code>
 *     FileWriter writer = new FileWriter("uriCache.txt");
 *     QueryHostBatcher getUris = dataMovementManager.newQueryHostBatcher(query)
 *       .withBatchSize(5000)
 *       .onUrisReady( new UrisToWriterListener(writer) )
 *       .onQueryFailure((client, exception) -> exception.printStackTrace());
 *     JobTicket getUrisTicket = dataMovementManager.startJob(getUris);
 *     getUris.awaitCompletion();
 *     dataMovementManager.stopJob(getUrisTicket);
 *     writer.flush();
 *     writer.close();
 *
 *     // now we have the uris, let's step through them
 *     BufferedReader reader = new BufferedReader(new FileReader("uriCache.txt"));
 *     QueryHostBatcher performDelete = dataMovementManager.newQueryHostBatcher(reader.lines().iterator())
 *       .onUrisReady(new DeleteListener())
 *       .onQueryFailure((client, exception) -> exception.printStackTrace());
 *     JobTicket ticket = dataMovementManager.startJob(performDelete);
 *     performDelete.awaitCompletion();
 *     dataMovementManager.stopJob(ticket);
 *</code></pre>
 * [merge timestamp]: https://docs.marklogic.com/guide/app-dev/point_in_time#id_32468
 */
```

**Comment by jmakeig** [comment]
<img width="914" alt="dmsdk-130" src="https://cloud.githubusercontent.com/assets/176233/18284679/c481794c-741f-11e6-821e-61057b036930.png">

**Comment by kcoleman-marklogic** [comment]
You can also use the javadoc code tag, plus pre, to address this. Thusly:
```
/** code sample: 
* <pre>{@code
 * doThis();
 * doThat();
 * }</pre>
 */
```

**Comment by sammefford** [comment]
Thanks for the proposals.  So much for "pure" markdown.  One reason I wanted to try this javadoc style because it also had an IDE plugin, but now I see it was only for InteliJ IDEA.  So I'll try your<pre>{@code and <pre><code>  suggestions.

**Comment by sammefford** [comment]
Based on the research I did for #619, this doesn't appear to be an issue unless your project is using the java-client-api source to generate the javadocs.  In other words, only people attempting to import java-client-api to develop it might be affected.  So we're not going to worry about this.
