### ISSUE TITLE
Decouple bulk processing from document transformation

### ISSUE THREAD

**Issue by jmakeig** [marklogic/data-movement#142]
Today, `ApplyTransformListener` assumes a URI in and a document out. That’s good for a default, but not flexible enough.

As a developer, I have a list of unique identifiers of employees. I might get that list from a document in a MarkLogic database or from somewhere else in my ETL app (e.g. live query to a remote database, file on the file system, piped from stdin). I want to run a bulk process, such that for each employee ID, I call some JavaScript/XQuery on the server to gather all the data related to that employee, apply some merge/transformation logic, and save a new, harmonized XML or JSON document for that employee. If the sources don't exist for a given employee (or another assertion failure during merge/transform) I might want to store a “marker” document and/or bubble up an exception/warning such that the orchestration (i.e. Java app) would be aware of an issue.

**Comment by paxtonhare** [comment]
@jmakeig this is inline with my thinking. Also aligns to actual Hub uses in the field. Don't require it to be a URI.

**Comment by sammefford** [comment]
Justin, I think were 90% of the way here.  Do you know about ApplyTransformListener.withApplyResult(IGNORE)?  That allows you to ignore the output of the transform so the transform script can do whatever it wants, including writing to the database.  I just tested, however, and if the REST /v1/internal/apply-transform endpoint is called with a non-existent uri, the server-side script is never run.  It shouldn't be too hard to add an option for it to run the transform with the context.uri but the content set to undefined or empty sequence.  Can you send that task on to Alex for 9.0.1?

**Comment by jmakeig** [comment]
@sammefford, would DMSDK interfaces need to change if this were pushed to 9.0-2? My gut says it’s unlikely that we get this in the REST API for 9.0-1. Is there way that we could engineer in some forward-compatibility such that we could roll this out in 9.0-2 without breaking anything?

**Comment by sammefford** [comment]
I think we're fine here to just add an option later.  We can just add an option to the REST endpoint and one to ApplyTransformListener

**Comment by jmakeig** [comment]
Moving the discussion to marklogic/java-client-api#538.
