### ISSUE TITLE
Write a DocumentWriteOperation using WriteHostBatcher

### ISSUE THREAD

**Issue by rjrudin** [marklogic/data-movement#144]
I noticed that WriteHostBatcher, at least on master, [`WriteHostBatcher`](https://github.com/marklogic/data-movement/blob/master/src/main/java/com/marklogic/datamovement/WriteHostBatcher.java) does not have a method that takes a `DocumentWriteOperation`. 

I think `DocumentWriteOperation` is one of the better features of the Java Client, since it encapsulates a write request in a single object. Could an `add(DocumentWriteOperation)` method be added to `WriteHostBatcher`?

**Comment by rjrudin** [comment]
I'm happy to take a crack at a PR for this too

**Comment by jmakeig** [comment]
@rjrudin That would be great.

**Comment by jmakeig** [comment]
Argh! I just realized that this is the marklogic/data-movement project. This repo has been deprecated in favor of marklogic/java-client-api since we rolled DMSDK into the mainline Java Client API. @rjrudin, can you please reproduce this issue there? Thanks and sorry for the confusion.
