### ISSUE TITLE
withOptionsFile(String optionsFilePath) method incorrectly passed to mlcp

### ISSUE THREAD

**Issue by srinathgit** [marklogic/data-movement#15]
Options file  specified using withOptionsFile(String optionsFilePath) method is passed incorrectly to mlcp. A typical scenario is as follows:

DEBUG: [MlcpMovementServices] args =[IMPORT -input_file_type rdf --options_file C:/MLSource/trunk/qa/mlcp/data/mlcp-graphs/seq1.txt -input_file_path C:/MLSource/trunk/qa/testdata/semantics/nquad.nq -host localhost -port 5275 -username admin -password admin]

Rather than passing -options_file <file_name>,  --options_file <file_name> is passed.  The ConfigConstants class, "OPTIONS_FILE "  variable already has a leading '-'.

public static final String OPTIONS_FILE = "-options_file";

**Comment by sammefford** [comment]
We're not moving forward with mlcp wrappers
