### ISSUE TITLE
Add redaction support to ExportDefinition

### ISSUE THREAD

**Issue by sammefford** [marklogic/data-movement#16]
ExportDefinition should support all new mlcp params for redaction

**Comment by sammefford** [comment]
We're not moving forward with the mlcp wrappers

**Comment by jmakeig** [comment]
But that raises the point of how to wire up redaction with export in DMSDK. As I understand it, redaction is just a server-side transform with code that's already there.

**Comment by kcoleman-marklogic** [comment]
I don't understand the concern you're raising, Justin.

Redaction rule sets are identified/applied by collection name. What would be needed from DMSDK, I would think, is just a way to specify what redaction rule collection(s) you want to apply to a given job.

Redaction rules are just documents that get inserted into the schemas database using the same tools available to insert any other document. Similarly, user-defined redaction functions (as opposed to "built-in" ones provided by ML) just get inserted into the modules database in the usual way. No special DMSDK mechanism is required for configuration of redaction.

**Comment by kcoleman-marklogic** [comment]
Sorry, I should have been more exact in my language. What would be needed from the DMSDK _interface_ is a way to specify the collection names. 

I have no idea how complex/simple it is for Sam to hook into the server side, obviously. On the server, it's exposed via the rdt:redact library function. Are there plans to surface this through REST in 9.0?

**Comment by jmakeig** [comment]
> Redaction rule sets are identified/applied by collection name. What would be needed from DMSDK, I would think, is just a way to specify what redaction rule collection(s) you want to apply to a given job.

Yes, but the actual redaction work is just an XQuery/JavaScript function. Just being able to call those functions, even without the rules would be useful. Applying the rules automagically would be the next step.

**Comment by kcoleman-marklogic** [comment]
I think that's contrary to some of the concepts and compliance requirements behind the feature. You might run it by Caio, though, to see. My understanding is that the exporter of the documents is not supposed to (have to) have control over the rules. Redaction is applied, both on the server and in mlcp, through collection name for more than mere convenience of reference.

Also, you can't "just call the functions". I mean, you can, of course. No one can stop you. :) 

However, the functions are designed to be backed by rules. The rules select which nodes in each document the functions act on (by XPath expression), as well as parameterizing the behavior. By the time you add all that to the DMSDK interfaces, you end up redefining the rules. Here's an example of a JSON rule that uses one of the built-in functions:
```
{rule: {
       path: '//ssn',
       method: {function: 'redact-us-ssn'},
       options: {level: 'partial'}
}}
```
You can get a ten cent tour or find more examples here: http://docs-ea.marklogic.com/guide/app-dev/redaction#chapter.

**Comment by sammefford** [comment]
My understanding was that redaction is only in mlcp for ML9, not REST or DMSDK.  The only reason we had this task open was to surface the feature if we got it for free via mlcp.

**Comment by jmakeig** [comment]
Yes, I understand the rules aspect. I'm trying to bridge the gap here: "You can do redaction on your own by calling this function we've helpfully included with the Server," without explicit policy support from DMSDK.

**Comment by kcoleman-marklogic** [comment]
I must just not understand what you're suggesting. The pre-defined functions are not designed to act on a whole document. They're scalpels, not bazookas. Anyway, from Sam says, this is all moot, so I'll shut up. :)

**Comment by sammefford** [comment]
Justin, I'm not sure your plan with this.  Since you re-opened it and assigned it to yourself, I re-read the history.  The only thing I want to add to the conversation is it appears that rdt.redact is a built-in that appears to operate on a set of documents, so it wouldn't be hard to add support to the REST endpoints and then the Java Client API and DMSDK ExportListener.

**Comment by jmakeig** [comment]
My plan is to allow DMSDK users to tap into redaction policies with `ExportListener`, for example, by specifying rule sets. I removed the milestone because we haven’t scheduled this for a release yet.

**Comment by jmakeig** [comment]
Migrated to marklogic/java-client-api#566.
