### ISSUE TITLE
make javadoc title configurable

### ISSUE THREAD

**Issue by sammefford** [marklogic/data-movement#17]
Make sure our gradle file is set up to accept a parameter to build javadocs with a configurable title.  This functionality is like we do for [java-client-api pom.xml](https://github.com/marklogic/java-client-api/blob/develop/pom.xml).

**Comment by rjrudin** [comment]
https://docs.gradle.org/current/dsl/org.gradle.api.tasks.javadoc.Javadoc.html#org.gradle.api.tasks.javadoc.Javadoc:title

**Comment by sammefford** [comment]
Thanks Rob!

**Comment by sammefford** [comment]
Ok, done.  Just run gradle with a -P "javadoc=your title" like so:

    gradle javadoc -P "javadocTitle=Some title"

**Comment by kcoleman-marklogic** [comment]
I cannot get this to work the way I need it to atm. With maven, I could do the following:
```
-Djavadoc-title="\${project.name} $G_JAVA_API_VERSION"
```
Where `project.name` was a maven property and $G_JAVA_API_VERSION is our override for the version. However, I cannot figure out how to use the equivalent of ${project.name} from the gradle command line. 

The desired gradle property is project.description, AFAICT, but for the life of me I can't seem to use it successfully in the -P arg, nor have I found examples of how to do this, so far. Do you know how to pull this off, @sammefford?

**Comment by sammefford** [comment]
I found the same thing, that I can't override built-ins using-P.  So I added an if-block in build.gradle just for you.  If you set "javadocTitle" vai -P just like I suggested, that's the title I use.  What am I missing?

**Comment by kcoleman-marklogic** [comment]
The problem is that I want to use the value of one of the gradle properties, `project.description`, as part of the value for javadocTitle, and I can't get it to work. Which is to say, I don't want to have to update the doc build just because you and Justin decide to change the name of the project from "data-movement" to "Samantha Mae Abertamanda".

**Comment by sammefford** [comment]
I see.  Would it be acceptable, then, to have you pass in "dataMovementVersion" and I can set the javadoc title to "${project.description} ${dataMovementVersion}"?  Like so:

    gradle javadoc -P "dataMovementVersion=3.2.1"

**Comment by kcoleman-marklogic** [comment]
Yes, as long as QA doesn't stick a timestamp or anything else complicated in the title. That's why it's not set up that way for java-client-api. Over there, QA uses something like `${project.name} ${project.version}-${timestamp}`, IIRC, so I could not simply override the version.

**Comment by sammefford** [comment]
Ok, we'll I'll make that change for now and we can change it again if there is a requirement from QA.

**Comment by kcoleman-marklogic** [comment]
Thanks, it looks like this is going to work out fine.
