### ISSUE TITLE
mlcp export

### ISSUE THREAD

**Issue by sammefford** [marklogic/data-movement#2]
Integrate mlcp export functionality under this API:

    DataMovementManager {
      ...
      JobTicket<ExportJobReport> export(ExportDefinition def)
      ExportDefinition newExportDefinition()
    }

    ExportDefinition implements JobDefinition<ExportDefinition> {
      ExportDefinition jobName(String jobName)
      ExportDefinition outputFilePath(String path)
      ExportDefinition outputCompress(boolean compress)
      ...
      ExportDefinition onModifyDocument(ExportModifyStringListener listener)
      ExportDefinition onModifyUri(ExportModifyUriListener listener)
      ExportDefinition onBatchSuccess(ExportSuccessListener listener)
      ExportDefinition onBatchFailure(ExportFailureListener listener)
    }

    ExportSuccessListener {
      void batchSuccess(ExportDocument[] docs)
    }

    ExportDocument {
      String getUri()
      Format getFormat()
      String getMimetype()
    }

    ExportFailureListener {
      void batchFailure(ExportFailure failure)
    }

    ExportFailure {
      String[] getBatchUris()
      Exception getException()
    }

**Comment by sammefford** [comment]
Here's the API we've landed on:

    ExportDefinition implements JobDefinition<ExportDefinition> {
      ExportDefinition withQueryFilter(CtsQueryDefinition query);
      ExportDefinition withCollectionFilter(String... forests);
      ExportDefinition withCompress(boolean compress);
      ExportDefinition withContentEncoding(String charset);
      ExportDefinition withCopyCollections(boolean copy);
      ExportDefinition withCopyPermissions(boolean copy);
      ExportDefinition withCopyProperties(boolean copy);
      ExportDefinition withCopyQuality(boolean copy);
      ExportDefinition withDirectoryFilter(String... directories);
      ExportDefinition withDocumentSelector(String xpath);
      ExportDefinition withIndented(boolean copy);
      ExportDefinition withMaxSplitSize(long splitSize);
      ExportDefinition withOutputFilePath(String path);
      ExportDefinition withOutputType(ExportDefinition.OutputType path);
      ExportDefinition withPathNamespace(String prefix, String namespaceUri);
      ExportDefinition withPathNamespaces(IterableNamespaceContext namespaces);
      ExportDefinition withSnapshot(boolean snapshot);
      ExportDefinition withTransform(DataMovementTransform<?> transform);
      ExportDefinition onBatchSuccess(BatchListener<ExportEvent> listener)
      ExportDefinition onOutputFileSuccess(BatchListener<ExportEvent> listener)
      ExportDefinition onBatchFailure(BatchFailureListener<ExportEvent> listener)

      enum OutputType { ARCHIVE, DOCUMENT };
    }

For now we haven't implemented any of the callbacks (onBatchSuccess, onOutputFileSucces, onBatchFailure).

**Comment by srinathgit** [comment]
Closing this out as DMSDK does not use mlcp
