### ISSUE TITLE
mlcp copy

### ISSUE THREAD

**Issue by sammefford** [marklogic/data-movement#3]
Integrate mlcp copy functionality under this API:

    DataMovementManager {
      ...
      JobTicket<CopyJobReport>   copy  (CopyDefinition def)
      CopyDefinition   newCopyDefinition()
    }

    CopyDefinition implements JobDefinition<CopyDefinition> {
      CopyDefinition jobName(String jobName)
      ...
      CopyDefinition onBatchSuccess(CopySuccessListener listener)
      CopyDefinition onBatchFailure(CopyFailureListener listener)
    }

    CopySuccessListener {
      void batchSuccess(String[] uris)
    }

    CopyFailureListener {
      void batchFailure(CopyFailure failure)
    }

    CopyFailure {
      String[] getBatchUris()
      Exception getException()
    }

**Comment by sammefford** [comment]
Here's the new API:

    CopyDefinition implements JobDefinition<CopyDefinition> {
      CopyDefinition withInputClient(DatabaseClient client);
      DatabaseClient getInputClient();
      CopyDefinition withOutputClient(DatabaseClient client);
      DatabaseClient getOutputClient();
      CopyDefinition withCollectionFilter(String... collections);
      String[] getCollectionFilter();
      CopyDefinition withCopyCollections(boolean copy);
      boolean getCopyCollections();
      CopyDefinition withCopyPermissions(boolean copy);
      boolean getCopyPermissions();
      CopyDefinition withCopyProperties(boolean copy);
      boolean getCopyProperties();
      CopyDefinition withCopyQuality(boolean copy);
      boolean getCopyQuality();
      CopyDefinition withDirectoryFilter(String... directories);
      String[] getDirectoryFilter();
      CopyDefinition withDocumentSelector(String xpath);
      String getDocumentSelector();
      CopyDefinition withFastload(boolean fastload);
      boolean getFastload();
      CopyDefinition withMaxSplitSize(long splitSize);
      long getMaxSplitSize();
      CopyDefinition withPathNamespace(String prefix, String namespaceUri);
      CopyDefinition withPathNamespaces(IterableNamespaceContext namespaces);
      IterableNamespaceContext getPathNamespaces();
      CopyDefinition withOutputCollections(String... collections);
      String[] getOutputCollections();
      CopyDefinition withOutputPermission(String role, String capability);
      CopyDefinition withOutputPermissions(String role, String capability, String... roleCapabilityPairs);
      String[] getOutputPermissions();
      CopyDefinition withOutputQuality(int quality);
      int getOutputQuality();
      CopyDefinition withOutputPartition(String partition);
      String getOutputPartition();
      CopyDefinition withOutputUriPrefix(String prefix);
      String getOutputUriPrefix();
      CopyDefinition withOutputUriReplacement(String pattern, String replacement);
      CopyDefinition withOutputUriReplacements(String pattern, String replacement, String...patternReplacementPairs);
      String[] getOutputUriReplace();
      CopyDefinition withOutputUriSuffix(String suffix);
      String getOutputUriSuffix();
      CopyDefinition withQueryFilter(CtsQueryDefinition query);
      CtsQueryDefinition getQueryFilter();
      CopyDefinition withSnapshot(boolean snapshot);
      boolean getSnapshot();
      CopyDefinition withTemporalCollection(String collection);
      String getTemporalCollection();
      CopyDefinition withTransform(DataMovementTransform<?> transform);
      DataMovementTransform<?> getTransform();
    }

**Comment by srinathgit** [comment]
Closing this out as DMSDK does not use mlcp
