### ISSUE TITLE
UnknownHostException when using localhost

### ISSUE THREAD

**Issue by jmakeig** [marklogic/data-movement#51]
By default, MarkLogic does some DNS magic to determine my fully qualified domain name as `macpro-2600.hsd1.ca.comcast.net`. However, when I try to connect with `localhost` I get an `java.net.UnknownHostException` . If I set the hostname explicitly in my MarkLogic configuration to `localhost` everything works, as expected.

Is this a DNS configuration issue in my environment? Has this not come up as an issue in the Java Client API? I’m confused as to how we got this far with `localhost` in the examples.

**Comment by sammefford** [comment]
A while back I made a change that uses the hostname for the request to the REST /v1/forestInfo endpoint.  So in single-node (e.g. development) cluster, only that hostname will be used, not the MarkLogic-assigned hostname.  So for single-node clusters, there's no futzing with DNS resolution required.  But in a multi-node cluster we're back to the same rule of "don't do that, silly", or "your hostnames for each ML Server must be DNS resolvable".
