### ISSUE TITLE
QueryHostBatcher with DeleteListener doesn’t delete all matching documents

### ISSUE THREAD

**Issue by jmakeig** [marklogic/data-movement#56]
The following code seems to consistently delete some, but not all of the documents in the `raw` collection. I’m running this on my laptop against a virgin 9.0-20160425 build using the out-of-the-box Documents database. Java 1.8.0_65.

```
package com.marklogic.datamovement.examples;

import com.marklogic.client.DatabaseClient;
import com.marklogic.client.DatabaseClientFactory;
import com.marklogic.client.DatabaseClientFactory.Authentication;
import com.marklogic.client.query.QueryDefinition;
import com.marklogic.client.query.StructuredQueryBuilder;
import com.marklogic.datamovement.DataMovementManager;
import com.marklogic.datamovement.DeleteListener;
import com.marklogic.datamovement.QueryHostBatcher;

/**
 * @author Justin Makeig <jmakeig@marklogic.com>
 *
 */
public class ClearByQuery {

	private static final DatabaseClient client = DatabaseClientFactory.newClient("localhost", 8000, "admin", "admin",
			Authentication.DIGEST);

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		DataMovementManager manager = DataMovementManager.newInstance().setClient(client);
		final StructuredQueryBuilder sqb = new StructuredQueryBuilder();
		final QueryDefinition query = sqb.collection("raw");
		QueryHostBatcher batcher = manager.newQueryHostBatcher(query)
				.onUrisReady(new DeleteListener())
				.onQueryFailure((client, throwable) -> {
					System.err.println("Error on " + throwable.getSourceUri());
				})
				.withBatchSize(2500);
		manager.startJob(batcher);
	}

}
```

**Comment by sammefford** [comment]
I'm sorry for the delay on this.  You need to call batcher.awaitTermination(limit, timeUnit).  Otherwise your main thread will exit before the QueryHostBatcher threads get a chance to finish.

**Comment by jmakeig** [comment]
> You need to call `batcher.awaitTermination(limit, timeUnit)`

Why does the developer have to specify this? Isn’t the batcher self-aware enough to figure this out itself? I'm missing something fundamental here.

**Comment by grechaw** [comment]
It's a long-running process thing -- something you'll appreciate the heck out of after the confusion of having to keep the process alive.

Sam I did notice that once a queryhostbatcher ws done the process did terminate, which was different from WriteHostBatcher, which just waits for more input.

**Comment by sammefford** [comment]
Justin, we could change it so that dataMovementManager.startJob(queryHostBatcher); blocks until the qhb has finished.  But, of course, that would be different than dataMovementManager.startJob(writeHostBatcher); which must not block so code can proceed to call writeHostBatcher.add . . .

Both QueryHostBatcher and WriteHostBatcher internally use a ThreadPoolExecutor, and we decided to surface the awaitCompletion(long, TimeUnit) and awaitTermination(long, TimeUnit) methods from ThreadPoolExecutor.  But I think we can do more here to make this more intuitive.

**Comment by grechaw** [comment]
Having an awaitTermination method is the right thing to do.    DMSDK orchestrates threads.  You need some way to say "I'm done spinning stuff up."  
There's no way to tell if DMSDK should shut down because many of the  queues are designed to be fed data in perpetuity.

**Comment by sammefford** [comment]
@jmakeig I'm thinking there's nothing for me to fix here.  Let me know if I'm overlooking something.
