### ISSUE TITLE
Ability to set format with addAs(uri, content) method

### ISSUE THREAD

**Issue by srinathgit** [marklogic/data-movement#60]
When I try to insert documents using addAs(String uri, Object content) method using an object of type ‘File’, I am able to write XML documents  and not json documents. When I try writing json documents, I get the following exception. We need to have the ability to set format  with this method

**com.marklogic.client.FailedRequestException: Local message: failed to apply resource at documents: Bad Request. Server Message: XDMP-DOCROOTTEXT: xdmp:get-request-part-body("xml") -- Invalid root text "{a:{b1:{c:&quot;jsonValue1&quot;}, b2:[&quot;b2 val1&quot;, &quot;b2 val2&quot;]}}" at  line 1**

**Comment by srinathgit** [comment]
I had used 'FileHandle'. The sample code  is

```
File fileJson = new File(WriteHostBatcherTest.class.getResource("dir.json").getFile());
FileHandle fileHandle	= new FileHandle(fileJson);
fileHandle.setFormat(Format.JSON);
WriteHostBatcher ihb1 =  dmManager.newWriteHostBatcher();
		ihb1.withBatchSize(1);
		ihb1.onBatchSuccess(
		        (client, batch) -> {
		        	for(WriteEvent w: batch.getItems()){
		        		System.out.println("Success:"+ w.getTargetUri()+":");
		        		successBatch.append(w.getTargetUri()+":");
		        	}
		         	
		          }
		        )
		        .onBatchFailure(
		          (client, batch, throwable) -> {
		        	  throwable.printStackTrace();
		        	  for(WriteEvent w: batch.getItems()){
		        		  System.out.println("Failure:"+ w.getTargetUri()+":");
		        		  failureBatch.append(w.getTargetUri()+":");
			        	}

		           
		          });
		
		// Issue with adding json using File Object
		ihb1.addAs("/doc/string",  fileJson);

```

The response is 
```
15:48:37.982 [pool-1-thread-1] DEBUG org.apache.http.wire - << "{"errorResponse":{"statusCode":400, "status":"Bad Request", "messageCode":"XDMP-DOCROOTTEXT", "message":"XDMP-DOCROOTTEXT: xdmp:get-request-part-body(\"xml\") -- Invalid root text \"{a:{b1:{c:&quot;jsonValue1&quot;}, b2:[&quot;b2 val1&quot;, &quot;b2 val2&quot;]}}\" at  line 1"}}"
com.marklogic.client.FailedRequestException: Local message: failed to apply resource at documents: Bad Request. Server Message: XDMP-DOCROOTTEXT: xdmp:get-request-part-body("xml") -- Invalid root text "{a:{b1:{c:&quot;jsonValue1&quot;}, b2:[&quot;b2 val1&quot;, &quot;b2 val2&quot;]}}" at  line 1
	at com.marklogic.client.impl.JerseyServices.checkStatus(JerseyServices.java:4626)
	at com.marklogic.client.impl.JerseyServices.postResource(JerseyServices.java:3594)
	at com.marklogic.client.impl.JerseyServices.postBulkDocuments(JerseyServices.java:3677)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:564)
	at com.marklogic.datamovement.impl.WriteHostBatcherImpl$BatchWriter.run(WriteHostBatcherImpl.java:747)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

````

**Comment by sammefford** [comment]
That should work fine if you use the add method rather than addAs, and pass fileHandle as the second argument.

**Comment by sammefford** [comment]
Ok, I made a small change so that I can still use the TemporalDocumentManager abilities of XMLDocumentManager without assuming that unspecified documents must be XML.

**Comment by srinathgit** [comment]
Sam,

1. What does this change mean to add() and addAs() methods in WriteHostBatcher ?
2. When I pass an unformatted xml to  addAs() method , the document gets inserted as a binary document . Is that an expected behavior ?

**Comment by sammefford** [comment]
The behavior should match databaseClient.newDocumentManager().writeAs(...).  The type of object you pass determines which handle is used which determines the format if the handle has a default.  For example, org.w3c.dom.Document is handled by DOMHandle which defaults to XML format. And com.fasterxml.jackson.databind.JsonNode is handled by JacksonHandle which defaults to JSON Format.  StringHandle doesn't have a default format.  I don't remember all the factors in that case.  Perhaps the extension on the uri has an effect.  If you want to ensure your document is written as a specific format, either use "add" with a handle with the format set or use "addAs" with an object type that is associated with a handle that defaults to your desired format.  

With that said, if you're seeing a case where WriteHostBatcher.addAs is behaving differently than databaseClient.newDocumentManager().writeAs, please report that as a new bug.

**Comment by srinathgit** [comment]
Shipping the task
