### ISSUE TITLE
Code DMSDK examples

### ISSUE THREAD

**Issue by sammefford** [marklogic/data-movement#70]
We need some examples in the code repository

**Comment by sammefford** [comment]
One example: get current collection count, load docs, get new count, check report against new count

**Comment by sammefford** [comment]
I'm not going to have time for anything more than javadocs and unit tests.  So I'll rely on PM to provide examples for EA users and Docs to provide examples for release.

**Comment by grechaw** [comment]
Um, maybe you shouldn't close but reassign?  Maybe PM + docs has a task already...

**Comment by grechaw** [comment]
I was going to comment that entity services does provide some DMSDK example code.
