### ISSUE TITLE
Remove logback dependency

### ISSUE THREAD

**Issue by sammefford** [marklogic/data-movement#88]
We wisely use slf4j so our customers can choose their preferred logging framework (log4j, commons logging, java.util.logging, or logback).  But we mistakenly include logback-classic in our pom.xml dependencies, thus forcing our clients to use logback-classic.  This is incorrect usage of slf4j according to this page: http://www.slf4j.org/manual.html

We should remove logback-classic from our pom.xml.  While at it, we should see if we can remove commons-logging.

**Comment by grechaw** [comment]
+1 to both.  This seems to be a common cleanup activity throughout open java development these days...

**Comment by sammefford** [comment]
Oops, this was supposed to be attached to java-client-api, not data-movement
