### ISSUE TITLE
Publish EA3 to Maven Central and jcenter

### ISSUE THREAD

**Issue by jmakeig** [marklogic/data-movement#90]
The plan is to publish the GA release to Maven Central and jcenter*. This allows developers to easily and automatically resolve dependencies and a host of other well known benefits. We should provide the same benefits for EA users. (This will also allow us to give a trial run of our publishing infrastructure.)

This will also require posting a snapshot build of the Java Client API build as well. (Also a good thing, but more work.)

* I don't know if we’ve explicitly specified jcenter, but it seems to be the up-and-coming competitor/complement to Maven Central.

**Comment by grechaw** [comment]
@sammefford pointed out elsewhere that we publish EA releases to the internal repo, which does allow public access, and should be sufficient for entity services examples.  As a release-related task for entity services, we'll update the examples dir to rely on the publicly available DMSDK and Java CLient API.

**Comment by sammefford** [comment]
Justin, is it ok if we hold off on this until GA?  We currently publish EA releases to our internal Maven server which seems to work fine as far as I can tell.  We already have good validation of our maven central publishing infrastructure through 8.x releases.  We can start pushing all future GA releases to jcenter also

**Comment by jmakeig** [comment]
Yes, I think our private repo is fine for EA. (Sorry about the churn on that.) My other related concern is that this artifact doesn’t generally show up until we ship. @popzip  and I need to begin developing examples for the EA3 sitelet based on the DMSDK and Java Client APIs. Can we shove a nightly up there every once in a while to support our ongoing content development?

**Comment by jmakeig** [comment]
Copying @rjrudin and @sastafford too.

**Comment by sammefford** [comment]
Kiran, let's discuss tomorrow whether Justin's request is do-able.

**Comment by hansenmc** [comment]
We publish CoRB2 to jcenter and maven central. If you publish to bintray, you can sync to maven central (if you satisfy the requirements to publish your source, javadocs, and pom has license info, etc). Take a look at the [build.gradle](https://github.com/marklogic/corb2/blob/master/build.gradle) for an example of how to publish and use the bintray task.

I have a MarkLogic bintray org, which CoRB2 is published under. I can add you as an admin with publish rights.

**Comment by sammefford** [comment]
We created #112 to address the request for a nightly build in our maven server.
