### ISSUE TITLE
Demonstrate pause/resume

### ISSUE THREAD

**Issue by jmakeig** [marklogic/data-movement#93]
Illustrate how to resume after a fatal error, for example a bug in server-side transformation code or the Java application that invokes the DMSDK. Track and report progress that has been made and pickup where things were left off without losing/repeating any data. Applicable to ingest, transform, and export.

**Comment by sammefford** [comment]
I think you could demonstrate how to do this with the current ingest/WriteHostBatcher.  You'll need the feature I just pushed this morning which sets batch.getJobBatchNumber().  But for QueryHostBatcher I think we'd need to add a way to skip past a certain number of matches so we can get back to a certain point we were at in the pagination when we chose to pause or encountered a catastrophic failure.  Perhaps QueryHostBatcher.withStart(long start)?

**Comment by jmakeig** [comment]
Migrated to marklogic/java-client-api#561.
