### ISSUE TITLE
Rename JAR to marklogic-data-movement-M.m-p.jar 

### ISSUE THREAD

**Issue by jmakeig** [marklogic/data-movement#95]
Today, the Data Movement SDK is packaged as `data-movement-M.m-p.jar`, for `M`ajor version, `m`inor , `p`atch. This makes it difficult to recognize, for example, in the classpath list of an IDE. A developer is likely looking for `marklogic` in the name somewhere. 

Update the artifact (and its references in Maven et al) to be `marklogic-data-movement-M.m-p.jar`. (Or should we just package this with the Java Client API?)

Some relevant external examples:

```xml
<dependency>
    <groupId>org.mongodb</groupId>
    <artifactId>mongodb-driver</artifactId>
    <version>3.3.0</version>
</dependency>
```

```xml
<dependency>
  <groupId>com.datastax.cassandra</groupId>
  <artifactId>cassandra-driver-core</artifactId>
  <version>3.1.0</version>
</dependency>
```

```xml
<dependency>
  <groupId>com.oracle.jdbc</groupId>
  <artifactId>ojdbc7</artifactId>
  <version>12.1.0.2</version>
</dependency>
```

**Comment by kcoleman-marklogic** [comment]
> (Or should we just package this with the Java Client API?)

I've been wondering about that myself. Would be good to figure this out soonish (say in the next 4-6 weeks) as it has bearing on the documentation. And testing, I imagine.

**Comment by srinathgit** [comment]
Closing the task as dmsdk is packaged with java client API
